'use strict';

const utils = require('./utils');
const { VERSION_FILE } = require('./version');

module.exports = {
    PROVIDER_FAMILIES: utils.PROVIDER_FAMILIES,
    PATHS: utils.PATHS,
    FEEDBACK_STATUS_TO_FOLDER: utils.FEEDBACK_STATUS_TO_FOLDER,
    FEEDBACK_FOLDER_TO_STATUS: utils.FEEDBACK_FOLDER_TO_STATUS,
    FEEDBACK_STATUS_FLAG_TO_FOLDER: utils.FEEDBACK_STATUS_FLAG_TO_FOLDER,
    FEEDBACK_ACTION_TO_STATUS: utils.FEEDBACK_ACTION_TO_STATUS,
    FEEDBACK_DEFAULT_LIST_FOLDERS: utils.FEEDBACK_DEFAULT_LIST_FOLDERS,
    AGENT_CONFIGS: utils.AGENT_CONFIGS,
    COMMAND_REGISTRY: utils.COMMAND_REGISTRY,
    COMMAND_ALIASES: utils.COMMAND_ALIASES,
    COMMAND_ALIAS_REVERSE: utils.COMMAND_ALIAS_REVERSE,
    COMMAND_ARG_HINTS: utils.COMMAND_ARG_HINTS,
    COMMANDS_DISABLE_MODEL_INVOCATION: utils.COMMANDS_DISABLE_MODEL_INVOCATION,
    MARKER_START: utils.MARKER_START,
    MARKER_END: utils.MARKER_END,
    VERSION_FILE,
};
