'use strict';

const utils = require('./utils');

module.exports = {
    readConductorReposFromGlobalConfig: utils.readConductorReposFromGlobalConfig,
    parseSimpleFrontMatter: utils.parseSimpleFrontMatter,
    normalizeDashboardStatus: utils.normalizeDashboardStatus,
    parseFeatureSpecFileName: utils.parseFeatureSpecFileName,
    inferDashboardNextCommand: utils.inferDashboardNextCommand,
    inferDashboardNextActions: utils.inferDashboardNextActions,
    getRecommendedActions: utils.getRecommendedActions,
    getAvailableActions: utils.getAvailableActions,
    getValidTransitions: utils.getValidTransitions,
    getSessionAction: utils.getSessionAction,
    isActionValid: utils.isActionValid,
    safeTmuxSessionExists: utils.safeTmuxSessionExists,
    collectDashboardStatusData: utils.collectDashboardStatusData,
    escapeForHtmlScript: utils.escapeForHtmlScript,
    buildDashboardHtml: utils.buildDashboardHtml,
    escapeAppleScriptString: utils.escapeAppleScriptString,
    captureDashboardScreenshot: utils.captureDashboardScreenshot,
    writeRepoRegistry: utils.writeRepoRegistry,
    readRadarMeta: utils.readRadarMeta,
    writeRadarMeta: utils.writeRadarMeta,
    removeRadarMeta: utils.removeRadarMeta,
    isRadarAlive: utils.isRadarAlive,
    sendMacNotification: utils.sendMacNotification,
    requestRadarJson: utils.requestRadarJson,
    renderRadarMenubarFromStatus: utils.renderRadarMenubarFromStatus,
    writeRadarLaunchdPlist: utils.writeRadarLaunchdPlist,
    RADAR_INTERACTIVE_ACTIONS: utils.RADAR_INTERACTIVE_ACTIONS,
    resolveRadarActionRepoPath: utils.resolveRadarActionRepoPath,
    parseRadarActionRequest: utils.parseRadarActionRequest,
    buildRadarActionCommandArgs: utils.buildRadarActionCommandArgs,
    runRadarInteractiveAction: utils.runRadarInteractiveAction,
    runRadarServiceDaemon: utils.runRadarServiceDaemon,
    parseLogFrontmatterFull: utils.parseLogFrontmatterFull,
    serializeLogFrontmatter: utils.serializeLogFrontmatter,
    updateLogFrontmatterInPlace: utils.updateLogFrontmatterInPlace,
    collectAnalyticsData: utils.collectAnalyticsData,
};
