'use strict';

const utils = require('./utils');

module.exports = {
    sanitizeForDns: utils.sanitizeForDns,
    getAppId: utils.getAppId,
    isPortAvailable: utils.isPortAvailable,
    allocatePort: utils.allocatePort,
    isProxyAvailable: utils.isProxyAvailable,
    loadProxyRegistry: utils.loadProxyRegistry,
    saveProxyRegistry: utils.saveProxyRegistry,
    loadPortRegistry: utils.loadPortRegistry,
    savePortRegistry: utils.savePortRegistry,
    registerPort: utils.registerPort,
    deregisterPort: utils.deregisterPort,
    scanPortsFromFilesystem: utils.scanPortsFromFilesystem,
    generateCaddyfile: utils.generateCaddyfile,
    reloadCaddy: utils.reloadCaddy,
    registerDevServer: utils.registerDevServer,
    deregisterDevServer: utils.deregisterDevServer,
    gcDevServers: utils.gcDevServers,
    detectDevServerContext: utils.detectDevServerContext,
    getDevProxyUrl: utils.getDevProxyUrl,
    getDevServerLogPath: utils.getDevServerLogPath,
    spawnDevServer: utils.spawnDevServer,
    waitForHealthy: utils.waitForHealthy,
    openInBrowser: utils.openInBrowser,
    resolveDevServerUrl: utils.resolveDevServerUrl,
    detectRadarContext: utils.detectRadarContext,
    registerRadarServer: utils.registerRadarServer,
    deregisterRadarServer: utils.deregisterRadarServer,
    resolveRadarUrl: utils.resolveRadarUrl,
    isProcessAlive: utils.isProcessAlive,
};
