'use strict';

/**
 * Paths that are noisy in feature-close logs but never meaningful merge/stash
 * blockers — Aigon session sidecars, telemetry, macOS junk, etc.
 *
 * Install-managed paths (agent templates, skills, applied-digest) are reset to
 * HEAD before merge instead of stashed — they are regenerated by `aigon apply`
 * and are unrelated to the feature being closed.
 */

const { SCAN_DIRS } = require('./install-manifest');

const INSTALL_MANAGED_EXACT = new Set([
    '.aigon/applied-digest',
    '.claude/settings.json',
    '.gemini/settings.json',
    '.cursor/hooks.json',
    '.cursor/cli.json',
]);

let manifestPathCache = null;

function clearInstallManifestPathCache() {
    manifestPathCache = null;
}

function getInstallManifestPathSet(repoRoot) {
    if (manifestPathCache && manifestPathCache.root === repoRoot) {
        return manifestPathCache.paths;
    }
    let paths = new Set();
    try {
        const { readManifestRecovering } = require('./install-manifest');
        const { manifest } = readManifestRecovering(repoRoot);
        paths = new Set((manifest?.files || []).map((entry) => entry.path));
    } catch (_) {
        paths = new Set();
    }
    manifestPathCache = { root: repoRoot, paths };
    return paths;
}

function normalizeWorkingTreePath(relPath) {
    return String(relPath || '').replace(/\\/g, '/').trim();
}

function isEphemeralWorkingTreePath(relPath) {
    const p = normalizeWorkingTreePath(relPath);
    if (!p) return false;
    if (p === '.DS_Store' || p.endsWith('/.DS_Store')) return true;
    if (p.startsWith('.aigon/sessions/')) return true;
    if (p.startsWith('.aigon/telemetry/')) return true;
    if (p.startsWith('.aigon/state/')) return true;
    if (p === '.aigon/sessions/events.jsonl') return true;
    return false;
}

function isInstallManagedWorkingTreePath(relPath, repoRoot) {
    const p = normalizeWorkingTreePath(relPath);
    if (!p) return false;
    if (INSTALL_MANAGED_EXACT.has(p)) return true;
    if (repoRoot) {
        const manifestPaths = getInstallManifestPathSet(repoRoot);
        if (manifestPaths.has(p)) return true;
    }
    return SCAN_DIRS.some((dir) => p === dir || p.startsWith(`${dir}/`));
}

function filterEphemeralWorkingTreePaths(paths) {
    return (paths || []).filter((p) => !isEphemeralWorkingTreePath(p));
}

function partitionWorkingTreeForClose(paths, repoRoot) {
    const installManaged = [];
    const user = [];
    for (const raw of paths || []) {
        const p = normalizeWorkingTreePath(raw);
        if (!p || isEphemeralWorkingTreePath(p)) continue;
        if (isInstallManagedWorkingTreePath(p, repoRoot)) installManaged.push(p);
        else user.push(p);
    }
    return { installManaged, user };
}

module.exports = {
    isEphemeralWorkingTreePath,
    isInstallManagedWorkingTreePath,
    filterEphemeralWorkingTreePaths,
    partitionWorkingTreeForClose,
    clearInstallManifestPathCache,
};
