import { withPro } from "../../../../components/pro-badge";

export default {
  board: "board",
  storage: "storage",
  "spec-layout": "spec-layout",
  "spec-view": "spec-view",
  server: "server",
  preview: "preview",
  config: "config",
  set: "set",
  nudge: "nudge",
  "dev-server": "dev-server",
  proxy: "proxy",
  "proxy-setup": "proxy-setup",
  deploy: "deploy",
  insights: { title: withPro("insights") },
  "agent-status": "agent-status",
  "agent-context": "agent-context",
  "sessions-close": "sessions-close",
  "session-list": "session-list",
  "token-window": "token-window",
  status: "status",
  repair: "repair",
  "security-scan": "security-scan",
  workflow: { title: withPro("workflow") },
  help: "help",
  next: "next",
};
